upstreams:
  - id: tender-frontend-dev
    name: tender-frontend-dev
    type: roundrobin
    scheme: http
    pass_host: pass
    hash_on: vars
    tls:
      verify: false
    nodes:
      "${DEV_TENDER_FRONTEND_UPSTREAM_HOST}:${DEV_TENDER_FRONTEND_UPSTREAM_PORT}": 0
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: dev
      app: tender

  - id: tender-api-dev
    name: tender-api-dev
    type: roundrobin
    scheme: http
    pass_host: pass
    hash_on: vars
    tls:
      verify: false
    nodes:
      "${DEV_TENDER_API_UPSTREAM_HOST}:${DEV_TENDER_API_UPSTREAM_PORT}": 0
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: dev
      app: tender
