routes:
  - id: gds-frontend-root-redirect-prod
    name: gds-frontend-root-redirect-prod
    uri: /data-platform
    plugins:
      redirect:
        uri: /data-platform/
        ret_code: 301
    priority: 100
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: gds

  - id: gds-frontend-prod
    name: gds-frontend-prod
    uri: /data-platform/*
    service_id: gds-frontend-prod
    priority: 0
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: gds

  - id: gds-external-frontend-prod
    name: gds-external-frontend-prod
    uri: /data-platform/*
    hosts:
      - jsc.shgas.com.cn
    service_id: gds-frontend-prod
    upstream_id: gds-external-frontend-prod
    priority: 0
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: gds

  - id: gds-api-prod
    name: gds-api-prod
    uri: /api/v1/*
    service_id: gds-api-prod
    plugin_config_id: gds-api-ip-rate-limit-prod
    plugins:
      forward-auth:
        uri: http://176.169.99.95/api/iam/auth/authz
        allow_degradation: false
        client_headers:
          - Forbidden-Reason
        keepalive: true
        keepalive_pool: 5
        keepalive_timeout: 60000
        request_headers:
          - Cookie
          - Client
        request_method: GET
        ssl_verify: false
        status_on_error: 403
        timeout: 3000
        upstream_headers:
          - X-User-Info
    priority: 0
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: gds
  - id: gds-no-login-prod
    name: gds-no-login-prod
    uri: /api/v1/dashboard/oa_portal
    service_id: gds-api-prod
    plugin_config_id: gds-api-ip-rate-limit-prod
    priority: 0
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: gds
  - id: gds-dashboard-prod
    name: gds-dashboard-prod
    uri: /webroot/*
    service_id: gds-api-prod
    priority: 0
    status: 1
    enable_websocket: false
    upstream_id: gds-dashboard-prod
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: gds
