services:
  - id: gds-frontend-prod
    name: gds-frontend-prod
    upstream_id: gds-frontend-prod
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: gds

  - id: gds-api-prod
    name: gds-api-prod
    upstream_id: gds-api-prod
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: gds
