packages:
  - 'apps/*'
  - 'gateway'
  - 'packages/*'
overrides:
  typescript: 6.0.3
allowBuilds:
  '@fission-ai/openspec': false
  bcrypt: true
  core-js: false
  core-js-pure: false
  es5-ext: false
  esbuild: true
  msgpackr-extract: true
  msw: false
  nice-napi: true
  simple-git-hooks: false
peerDependencyRules:
  allowedVersions:
    dva-core: '2'
    less-loader: '11 || 12'
    postcss: '8'
    react: '18'
    react-dom: '18'
ignoredBuiltDependencies:
  - '@prisma/engines'
  - '@scarf/scarf'
  - prisma
  - prisma-zod-generator
minimumReleaseAgeExclude:
  - '@bull-board/api@8.0.2'
  - '@bull-board/hono@8.0.2'
  - '@bull-board/ui@8.0.2'
