services:
  - id: "00000000000000000436"
    name: tender-test
    hosts:
      - 176.169.99.95
      - 176.169.99.150
    upstream:
      hash_on: vars
      nodes:
        - priority: 0
          host: 176.169.99.150
          port: 18091
          weight: 0
      pass_host: pass
      scheme: http
      tls:
        verify: false
      type: roundrobin
    plugins:
      proxy-rewrite:
        regex_uri:
          - ^/api/tender/(.*)
          - /$1
        use_real_request_uri_unsafe: false
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: dev
      app: tender
