routes:
  - id: "00000000000000000018"
    name: /prod/gds
    uri: /api/v1/*
    service_id: "00000000000000000466"
    plugins:
      forward-auth:
        uri: http://176.169.99.125/api/iam/auth/authz
        allow_degradation: false
        client_headers:
          - Forbidden-Reason
        keepalive: true
        keepalive_pool: 5
        keepalive_timeout: 60000
        request_headers:
          - Cookie
          - Client
        request_method: GET
        ssl_verify: false
        status_on_error: 403
        timeout: 3000
        upstream_headers:
          - X-User-Info
    priority: 0
    status: 1
    enable_websocket: false
  - id: "00000000000000000635"
    name: /prod/tender
    uri: /api/tender/*
    service_id: "00000000000000000567"
    plugins:
      forward-auth:
        uri: http://176.169.99.125/api/iam/auth/authz
        allow_degradation: false
        client_headers:
          - Forbidden-Reason
        keepalive: true
        keepalive_pool: 5
        keepalive_timeout: 60000
        request_headers:
          - Cookie
          - Client
          - Authorization
        request_method: GET
        ssl_verify: false
        status_on_error: 403
        timeout: 3000
        upstream_headers:
          - X-User-Info
    priority: 0
    status: 1
    enable_websocket: false
  - id: "00000000000000000746"
    name: /prod/tender/thirdparty
    uri: /thirdparty/tender/*
    service_id: "00000000000000000567"
    plugins:
      forward-auth:
        uri: http://176.169.99.125/api/iam/auth/internal-authz
        allow_degradation: false
        client_headers:
          - Forbidden-Reason
        keepalive: true
        keepalive_pool: 5
        keepalive_timeout: 60000
        request_headers:
          - Cookie
          - apikey
          - IP-Chain
          - Authorization
        request_method: GET
        ssl_verify: false
        status_on_error: 403
        timeout: 3000
        upstream_headers: {}
      proxy-rewrite:
        regex_uri:
          - ^/thirdparty/tender/(.*)
          - /thirdparty/$1
        use_real_request_uri_unsafe: false
    priority: 0
    status: 1
    enable_websocket: false
  - id: "00000000000000000784"
    name: /prod/tender/public
    uris:
      - /api/tender/public/*
      - /api/tender/weaver/*
    service_id: "00000000000000000567"
    priority: 0
    status: 1
    enable_websocket: false
  - id: "00000000000000000885"
    name: /prod/gds/no-login
    uri: /api/v1/dashboard/oa_portal
    service_id: "00000000000000000466"
    priority: 0
    status: 1
    enable_websocket: false
