routes:
  - id: tender-frontend-prod
    name: tender-frontend-prod
    uris:
      - /tender
      - /tender/*
      - /tender-portal
      - /tender-portal/*
    service_id: tender-frontend-prod
    priority: 0
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender
  - id: tender-frontend-external-prod
    name: tender-frontend-external-prod
    hosts:
      - tender.shgas.com.cn
    uris:
      - /tender
      - /tender/*
      - /tender-portal
      - /tender-portal/*
    service_id: tender-frontend-prod
    upstream:
      hash_on: vars
      nodes:
        - priority: 0
          host: 176.169.99.125
          port: 81
          weight: 0
      pass_host: pass
      scheme: http
      tls:
        verify: false
      type: roundrobin
    priority: 0
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender

  - id: tender-api-prod
    name: tender-api-prod
    uri: /api/tender/*
    service_id: tender-api-prod
    plugins:
      forward-auth:
        uri: http://176.169.99.95/api/iam/auth/authz
        allow_degradation: false
        client_headers:
          - Forbidden-Reason
        keepalive: true
        keepalive_pool: 5
        keepalive_timeout: 60000
        request_headers:
          - Cookie
          - Client
          - Authorization
        request_method: GET
        ssl_verify: false
        status_on_error: 403
        timeout: 3000
        upstream_headers:
          - X-User-Info
    priority: 0
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender
  - id: tender-thirdparty-prod
    name: tender-thirdparty-prod
    uri: /thirdparty/tender/*
    service_id: tender-api-prod
    plugins:
      forward-auth:
        uri: http://176.169.99.95/api/iam/auth/internal-authz
        allow_degradation: false
        client_headers:
          - Forbidden-Reason
        keepalive: true
        keepalive_pool: 5
        keepalive_timeout: 60000
        request_headers:
          - Cookie
          - apikey
          - IP-Chain
          - Authorization
        request_method: GET
        ssl_verify: false
        status_on_error: 403
        timeout: 3000
        upstream_headers: {}
      proxy-rewrite:
        regex_uri:
          - ^/thirdparty/tender/(.*)
          - /thirdparty/$1
        use_real_request_uri_unsafe: false
    priority: 0
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender
  - id: tender-public-prod
    name: tender-public-prod
    uris:
      - /api/tender/public/*
      - /api/tender/weaver/*
    service_id: tender-api-prod
    priority: 0
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender
  - id: tender-minio-prod
    name: tender-minio-prod
    uri: /minio/*
    service_id: tender-api-prod
    upstream:
      hash_on: vars
      nodes:
        - priority: 0
          host: 176.169.99.125
          port: 9000
          weight: 0
      pass_host: pass
      scheme: http
      timeout:
        connect: 300
        read: 300
        send: 300
      tls:
        verify: false
      type: roundrobin
    priority: 0
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender
