upstreams:
  - id: iam-api-dev
    name: iam-api-dev
    desc: IAM public API upstream for local development
    type: roundrobin
    scheme: http
    pass_host: pass
    nodes:
      api:30000: 1
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: dev

  - id: iam-admin-api-dev
    name: iam-admin-api-dev
    desc: IAM admin API upstream for local development
    type: roundrobin
    scheme: http
    pass_host: pass
    nodes:
      admin-api:30001: 1
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: dev

  - id: iam-sso-frontend-dev
    name: iam-sso-frontend-dev
    desc: IAM SSO frontend nginx upstream for local development
    type: roundrobin
    scheme: http
    pass_host: pass
    nodes:
      sso:80: 1
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: dev

  - id: iam-admin-frontend-dev
    name: iam-admin-frontend-dev
    desc: IAM admin frontend nginx upstream for local development
    type: roundrobin
    scheme: http
    pass_host: pass
    nodes:
      admin:80: 1
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: dev
