services:
  - id: iam-api-prod
    name: iam-api-prod
    desc: IAM public API production baseline
    upstream_id: iam-api-prod
    plugins:
      prometheus:
        prefer_name: true
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: iam

  - id: iam-admin-api-prod
    name: iam-admin-api-prod
    desc: IAM admin API production baseline
    upstream_id: iam-admin-api-prod
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: iam

  - id: iam-oidc-provider-prod
    name: iam-oidc-provider-prod
    desc: IAM OIDC provider production baseline
    upstream_id: iam-oidc-provider-prod
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: iam

  - id: iam-sso-frontend-prod
    name: iam-sso-frontend-prod
    desc: IAM SSO frontend production baseline
    upstream_id: iam-sso-frontend-prod
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: iam

  - id: iam-admin-frontend-prod
    name: iam-admin-frontend-prod
    desc: IAM admin frontend production baseline
    upstream_id: iam-admin-frontend-prod
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: iam
