services:
  - id: gds-frontend-dev
    name: gds-frontend-dev
    upstream_id: gds-frontend-dev
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: dev
      app: gds
  - id: gds-api-dev
    name: gds-api-dev
    upstream_id: gds-api-dev
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: dev
      app: gds
