services:
  db:
    image: docker.xuanyuan.run/postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: iam
      POSTGRES_PASSWORD: iam_password
      POSTGRES_DB: iam_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iam -d iam_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: docker.xuanyuan.run/library/redis:latest
    restart: unless-stopped
    ports:
      - "6390:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    ports:
      - "30011:30000"
    environment:
      DATABASE_URL: postgresql://iam:iam_password@db:5432/iam_db
      REDIS_URL: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      PORT: 30000
      NODE_ENV: development
      LOG_LEVEL: info
      IAM_SECRET_KEY: shenergy2020
      PASSWORD_HASH_ROUNDS: 10
      DEFAULT_USER_PASSWORD: default123
      MAGIC_CODE: 1234
      CAP_ENABLED: true
      WX_CORPID: "wwddf8d65300d53eb1"
      WX_CORPSECRET: "L41cYOgd-wmFEmoHPHXIL6ZHiP-hMzuXT_wsWINjAes"
      SMS_URL: "http://176.169.86.35:17111/v1/thirdparty/common/sms/sendMsg3"
      SMS_SIGNATURE_KEY: "aa8099eb32c945f39157f339d8fd702c"
      ORCAS_URL: "http://176.169.99.150:18091/orcas/login"
      PURVEYOR_PARENT_ORG: "GY"
      REDIS_EXPIRE_TIME: 86400
      AUTH_CODE_EXPIRE_TIME: 300
      LOGIN_ENDPOINT: /portal/login
      AUTHORIZATION_ENDPOINT: /sso/authorize
      LOGOUT_ENDPOINT: /sso/logout
      THIRDPARTY_OA_ENDPOINT: /sso/thirdparty/oa
      HTTP_PROXY: http://176.169.105.96:3928
      HTTPS_PROXY: http://176.169.105.96:3928
      NO_PROXY: localhost,127.0.0.1,176.169.99.191,176.169.99.95,180.50.65.131,192.168.0.0/16,176.169.99.125,176.169.86.35
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  admin-api:
    build:
      context: ..
      dockerfile: apps/admin-api/Dockerfile
    restart: unless-stopped
    ports:
      - "30012:30001"
    environment:
      DATABASE_URL: postgresql://iam:iam_password@db:5432/iam_db
      REDIS_URL: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      PORT: 30001
      NODE_ENV: production
      LOG_LEVEL: info
      PASSWORD_HASH_ROUNDS: 10
      ADMIN_CLIENT_CODES: iam-admin
      ADMIN_ROLE_CODES: iam:admin
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  db_data:
  redis_data:
