routes:
  - id: gds-api-dev
    name: gds-api-dev
    uri: /api/v1/*
    service_id: gds-api-dev
    plugins:
      forward-auth:
        uri: http://176.169.99.191:9080/api/iam/auth/authz
        allow_degradation: false
        client_headers:
          - Forbidden-Reason
        keepalive: true
        keepalive_pool: 5
        keepalive_timeout: 60000
        request_headers:
          - Cookie
          - Client
          - Authorization
        request_method: GET
        ssl_verify: false
        status_on_error: 403
        timeout: 3000
        upstream_headers:
          - X-User-Info
    priority: 0
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: dev
      app: gds
  - id: gds-no-login-dev
    name: gds-no-login-dev
    uri: /api/v1/dashboard/oa_portal
    service_id: gds-api-dev
    priority: 0
    status: 1
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: dev
      app: gds
