services:
  - id: tender-frontend-prod
    name: tender-frontend-prod
    upstream_id: tender-frontend-prod
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender

  - id: tender-api-prod
    name: tender-api-prod
    upstream_id: tender-api-prod
    plugins:
      client-control:
        max_body_size: 0
      proxy-rewrite:
        regex_uri:
          - ^/api/tender/(.*)
          - /$1
        use_real_request_uri_unsafe: false
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender
