services:
  - id: tender-frontend-prod
    name: tender-frontend-prod
    upstream:
      hash_on: vars
      nodes:
        - priority: 0
          host: 176.169.99.125
          port: 80
          weight: 0
      pass_host: pass
      scheme: http
      tls:
        verify: false
      type: roundrobin
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender

  - id: tender-api-prod
    name: tender-api-prod
    upstream:
      hash_on: vars
      nodes:
        - priority: 0
          host: 176.169.99.125
          port: 18091
          weight: 0
      pass_host: pass
      scheme: http
      timeout:
        connect: 300
        read: 300
        send: 300
      tls:
        verify: false
      type: roundrobin
    plugins:
      client-control:
        max_body_size: 0
      proxy-rewrite:
        regex_uri:
          - ^/api/tender/(.*)
          - /$1
        use_real_request_uri_unsafe: false
    enable_websocket: false
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender
