upstreams:
  - id: tender-frontend-prod
    name: tender-frontend-prod
    type: roundrobin
    scheme: http
    pass_host: pass
    hash_on: vars
    tls:
      verify: false
    nodes:
      "${PROD_TENDER_FRONTEND_UPSTREAM_HOST}:${PROD_TENDER_FRONTEND_UPSTREAM_PORT}": 0
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender

  - id: tender-frontend-external-prod
    name: tender-frontend-external-prod
    type: roundrobin
    scheme: http
    pass_host: pass
    hash_on: vars
    tls:
      verify: false
    nodes:
      "${PROD_TENDER_FRONTEND_EXTERNAL_UPSTREAM_HOST}:${PROD_TENDER_FRONTEND_EXTERNAL_UPSTREAM_PORT}": 0
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender

  - id: tender-api-prod
    name: tender-api-prod
    type: roundrobin
    scheme: http
    pass_host: pass
    hash_on: vars
    timeout:
      connect: 300
      read: 300
      send: 300
    tls:
      verify: false
    nodes:
      "${PROD_TENDER_API_UPSTREAM_HOST}:${PROD_TENDER_API_UPSTREAM_PORT}": 0
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender

  - id: tender-minio-prod
    name: tender-minio-prod
    type: roundrobin
    scheme: http
    pass_host: pass
    hash_on: vars
    timeout:
      connect: 300
      read: 300
      send: 300
    tls:
      verify: false
    nodes:
      "${PROD_TENDER_MINIO_UPSTREAM_HOST}:${PROD_TENDER_MINIO_UPSTREAM_PORT}": 0
    labels:
      managed_by: shgas-iam
      source: repo-manifest
      env: prod
      app: tender
