export enum ApiErrorCode {
  AdminClientSecretReadAuditFailed = "ADMIN_CLIENT_SECRET_READ_AUDIT_FAILED",
  InternalError = "COMMON.INTERNAL_ERROR",
  NotFound = "COMMON.NOT_FOUND",
  BadRequest = "COMMON.BAD_REQUEST",
  ValidationFailed = "COMMON.VALIDATION_FAILED",

  Unauthorized = "AUTH.UNAUTHORIZED",
  Forbidden = "AUTH.FORBIDDEN",
  Maintenance = "AUTH.MAINTENANCE",
  SessionInvalid = "SESSION_INVALID",
  SubjectAccessUnavailable = "SUBJECT_ACCESS_UNAVAILABLE",

  InvalidLoginCredential = "LOGIN.INVALID_CREDENTIAL",
  LoginFailed = "LOGIN.FAILED",
  InvalidVerificationCode = "LOGIN.INVALID_VERIFICATION_CODE",
  HumanVerificationRequired = "LOGIN.HUMAN_VERIFICATION_REQUIRED",
  LoginProtectionUnavailable = "LOGIN_PROTECTION_UNAVAILABLE",
  AdminLoginStateUnavailable = "ADMIN_LOGIN_STATE_UNAVAILABLE",
  AdminLoginStateAuditFailedAfterEffect = "ADMIN_LOGIN_STATE_AUDIT_FAILED_AFTER_EFFECT",
  AdminSessionCurrentProtected = "ADMIN_SESSION_CURRENT_PROTECTED",
  AdminMutationCommitted = "ADMIN_MUTATION_COMMITTED",

  InvalidHumanVerificationSite = "HUMAN_VERIFICATION.INVALID_SITE",

  SmsCooldown = "SMS.COOLDOWN",
  SmsSendFailed = "SMS.SEND_FAILED",
  SmsUnavailable = "SMS.UNAVAILABLE",

  UserNotFound = "USER.NOT_FOUND",
  UsernameAlreadyExists = "USER.USERNAME_ALREADY_EXISTS",
  InvalidMobile = "USER.INVALID_MOBILE",
  MobileAlreadyExists = "USER.MOBILE_ALREADY_EXISTS",
  WeakPassword = "USER.WEAK_PASSWORD",
  InvalidOldPassword = "USER.INVALID_OLD_PASSWORD",
  UserHasActiveEmployment = "USER.HAS_ACTIVE_EMPLOYMENT",
  UserSearchResultTooLarge = "USER_SEARCH_RESULT_TOO_LARGE",
  UserSearchUnavailable = "USER_SEARCH_UNAVAILABLE",

  OrganizationNotFound = "ORG.NOT_FOUND",
  OrganizationAlreadyExists = "ORG.ALREADY_EXISTS",
  OrganizationCodeExists = "ORG.CODE_EXISTS",
  OrganizationHasChildren = "ORG.HAS_CHILDREN",
  OrganizationHasEmployment = "ORG.HAS_EMPLOYMENT",
  OrganizationHasOpenResponsibilityAssignment = "ORG.HAS_OPEN_RESPONSIBILITY_ASSIGNMENT",

  PositionNotFound = "POSITION.NOT_FOUND",
  PositionCodeExists = "POSITION.CODE_EXISTS",
  PositionHasEmployment = "POSITION.HAS_EMPLOYMENT",

  EmploymentNotFound = "EMPLOYMENT.NOT_FOUND",
  EmploymentNotEditable = "EMPLOYMENT.NOT_EDITABLE",
  EmploymentAlreadyExists = "EMPLOYMENT.ALREADY_EXISTS",

  OrganizationResponsibilityAssignmentNotFound = "ORG_RESPONSIBILITY.ASSIGNMENT_NOT_FOUND",
  OrganizationResponsibilityAssignmentNotOpen = "ORG_RESPONSIBILITY.ASSIGNMENT_NOT_OPEN",
  OrganizationResponsibilityHolderEmploymentUnavailable = "ORG_RESPONSIBILITY.HOLDER_EMPLOYMENT_UNAVAILABLE",
  OrganizationResponsibilityTargetOrganizationUnavailable = "ORG_RESPONSIBILITY.TARGET_ORGANIZATION_UNAVAILABLE",
  OrganizationResponsibilityAssignmentDuplicateOpen = "ORG_RESPONSIBILITY.ASSIGNMENT_DUPLICATE_OPEN",
  OrganizationResponsibilityAssignmentCardinalityConflict = "ORG_RESPONSIBILITY.ASSIGNMENT_CARDINALITY_CONFLICT",
  OrganizationResponsibilityAssignmentUnmanageableConflict = "ORG_RESPONSIBILITY.ASSIGNMENT_UNMANAGEABLE_CONFLICT",

  ClientNotFound = "CLIENT.NOT_FOUND",
  ClientCodeExists = "CLIENT.CODE_EXISTS",

  RoleNotFound = "ROLE.NOT_FOUND",
  RoleCodeExists = "ROLE.CODE_EXISTS",
  RoleHasAssignment = "ROLE.HAS_ASSIGNMENT",
  RoleAssignmentExists = "ROLE.ASSIGNMENT_EXISTS",
  InvalidRoleAssignmentScope = "ROLE.INVALID_ASSIGNMENT_SCOPE",
  RoleAssignmentTargetNotFound = "ROLE.ASSIGNMENT_TARGET_NOT_FOUND",

  InvalidSsoClient = "SSO.INVALID_CLIENT",
  InvalidRedirectUri = "SSO.INVALID_REDIRECT_URI",
  InvalidAuthCode = "SSO.INVALID_AUTH_CODE",
  SubjectProjectionNotReady = "SUBJECT_PROJECTION_NOT_READY",

  PrivilegeDelegationNotFound = "PRIVILEGE.DELEGATION_NOT_FOUND",
  PrivilegeDelegationEnded = "PRIVILEGE.DELEGATION_ENDED",
  PrivilegeDelegationResolutionInputNotFound = "PRIVILEGE.DELEGATION_RESOLUTION_INPUT_NOT_FOUND",
  PrivilegeDelegationResolutionUnavailable = "PRIVILEGE.DELEGATION_RESOLUTION_UNAVAILABLE",
  PrivilegeNotFound = "PRIVILEGE.NOT_FOUND",
  PrivilegeAlreadyDelegated = "PRIVILEGE.ALREADY_DELEGATED",

  OrcasLoginFailed = "INTEGRATION.ORCAS_LOGIN_FAILED",
}
